### ISSUE TITLE
standard dynamic scatter plots in NeMO have no x and y axis labels

### ISSUE THREAD

**Issue by carlocolantuoni** [nemoarchive/analytics#103]

**Comment by carlocolantuoni** [comment]
am i missing how to do this?

**Comment by carlocolantuoni** [comment]
@jorvis you mentioned this was due to brian g efforts to maximize space in the plots. Can u add the option of having or not having these labels when creating the view in "curate"?

**Comment by carlocolantuoni** [comment]
@adkinsrs this may be the simplest one to start with - right now no axis labels are added - we could let users choose if they want them or not (grabing them from the meta data the user selected for the plot, and the gene being plotted

**Comment by adkinsrs** [comment]
@carlocolantuoni do you have a URL for an example display?

**Comment by carlocolantuoni** [comment]
Just a label under the x axis and a label at left of y axis corresponding to the data being plotted . We can talk more tue noon if that works

**Comment by carlocolantuoni** [comment]
so the y-axis label can be the gene that was searched for if expression is on the y-axis. if the user has selected something else, the user selected element from the Y pull down

the x-axis labels should be the element specified by the user in the X pull down menu

**Comment by adkinsrs** [comment]
@carlocolantuoni I deployed this to devel.umgear.org just a second ago.  Right now the axes will only have titles if the y-axis is "expression" but I am happy to make more modifications with this.

Right now my largest difficulty is that the axes are pushed out of the plot box if the plot is too wide or too tall.  While I did make some adjustments to minimize that from happening, it still may happen from time to time.  There is still another minor issue of the axis title text overlapping with the tick labels, but I could potentially just cap the number of characters in the label.

**Comment by adkinsrs** [comment]
The axis labels are added but some modification needs to happen with the margin settings so the placement is consistent when viewing in the dataset curator vs the gene search display page.  If I fix it to look good on one page, it will look off on the next page.

I'm closing this ticket because this issue is mentioned in https://github.com/jorvis/gEAR/issues/784
