### ISSUE TITLE
projectR implementation in NeMO Analytics

### ISSUE THREAD

**Issue by carlocolantuoni** [nemoarchive/analytics#104]
Hi guys,

Another much more streamlined version of projectR implementation has come up in my head. It would most definitely be a phase1 that would have to be followed by a phase2 that would be like what brian and i have been storyboarding, but i think this would give maximum functionality for minimum software engineering:

Already, the NeMO front page has a gene search box followed by visualizations of the requested gene in many datasets. Lets leverage all this directly for projection. In addition to the gene search box we could simply add the ability to find 1] dimensions that have been calculated within other NeMO datasets. Thus would entail a live pulldown menu that searches the uns element of the h5's to populate this pull down with any dimension reduction that has been saved in any of the NeMO datasets. 2] gene lists that we have collected to use as projections. This would require us to put the list/db of gene lists somewhere it is easy to grab from the front NeMO page.

User could select a dimension or gene list,  projection is done in R in the background (or pulled up if already done) and the default profile and visualization would come up, just as if the user had requested a gene, but we would now b looking at a more complex dimension in the data. No new pages to design.

This would require only the addition of projection based pulldown menus to the main NeMO page plus some code to project (just a few lines in an R session in the back).  No new complicated visualization pages etc - we'd be using the same page as we use for showing genes, just showing other dimensions.

what do u think of this?

**Comment by carlocolantuoni** [comment]
these are notes i sent to us previously on email and may be useful at later points:

Hi guys,

Seth - I see your point about trying to select an approach that yields new usable elements of NeMO Analytics in the short term, and you heard my concern about not dropping key  functionality if it is not the 1st to be implemented. I propose that to satisfy both of these concerns, we could build the "full" dimension reduction in one data set followed by projection across many data sets for PCA only. This would leave all the headaches and in and outs of the NMF, clustering and other dimension reduction tools for later. What do you guys think?

Here is an outline of how that PCA projection workflow would go - paralleling the storyboard Brian presented today. Brian, can u sent those slides around to the group?

Joshua - let me know if this makes sense. we can provide more details at each step - let us know what you need after this initial outline to get you going.

#USERviaGUI#
selects "Dimension Reduction" under "Analyze" for DataSet1 of interest from the NeMO front page.
selects "PCA" under "Dimension Reduction" (only option for now).

#python#
expression matrix for DataSet1 is fetched from h5 object.

#python-OR-R#
PCA is done on the expression matrix.

#python#
Elements of PCA to be saved:
1]Sample/Cell positions/scores in each PC - saved as sample metadata for DataSet1 (used for plotting of this data set below, just like a gene can be: "DataSet1$SampleScores" ).
2]Gene weights for each PC - saved as dimension reduction for DataSet1 (used in projection below: "DataSet1$GeneWeights").

#GUIbacktoUSER#
"Your PCA on DataSet1 has been completed."

#USERviaGUI#
selects "Projection" under "Analyze" for DataSet1 of interest from the NeMO front page.
selects "PCA" under "Projection" (only option for now).
selects "PC1" and "PC2" under "PCA".
selects "DataSet2" to be projected into this transcriptional space.

#python#
expression matrix for DataSet2 is fetched from h5 object

#R#
projectedDataSet2=projectR(data= DataSet2, weights= DataSet1$GeneWeights)
the projectR function returns projectedDataSet2 as a vector of numeric values, 1 value for each sample in DataSet2.

#python#
projectedDataSet2 is added to DataSet2 h5 as sample metadata (used to plot or color DataSet2 below).

#GUIbacktoUSER#
display DataSet1 PCs (using default views already defined for DataSet1, but using DataSet1$SampleScores instead of genes for display) along side these same PCs projected into DataSet2 (again default views for DataSet2, but using projectedDataSet2 just like gene values for display).

**Comment by adkinsrs** [comment]
Closing in favor of IGS/gEAR#243
