### ISSUE TITLE
Sometimes profiles do not appear

### ISSUE THREAD

**Issue by jorvis** [nemoarchive/analytics#110]
Reported by Ronna:

> This happened a few times in the past week. When I try to go onto nemoanalytics I can't get into any profile. This is not a cache issue, in my opinion, as it happens also after I restart my computer and did not resolve with 4-5 hard refreshes.
> 
> I wanted to see what it looks like and can't get pass:
> 
> [image: image.png]
> 
> The different profiles do not show. I'm logged in as curator and using
> chrome.
> 
> Sorry to report this..
> Ronna

**Comment by jorvis** [comment]
@hertzron Could you try again using the web interface to attach the screenshot?  However you did it that time didn't work.

**Comment by hertzron** [comment]
Hi,

I just tried again and still not working.

Is this what you are looking for?

[image: image.png]

Ronna

**Comment by jorvis** [comment]
How are you trying to attach an image?  It doesn't work if you reply to the e-mail for example.  You have to open GitHub and use the interface to attach the image.

**Comment by hertzron** [comment]
[image: image.png]

**Comment by jorvis** [comment]
OK, works now.  This was an issue on my end.
