### ISSUE TITLE
violin plots presenting as thin lines instead of traditional violin plots

### ISSUE THREAD

**Issue by hertzron** [nemoarchive/analytics#118]
![image](https://user-images.githubusercontent.com/17456863/85350330-dfd8a000-b4ce-11ea-9fc3-f14d366379e1.png)

**Comment by adkinsrs** [comment]
@hertzron what is the URL for this dataset?

**Comment by adkinsrs** [comment]
Discussed with @hertzron on Tuesday that this may be a byproduct of the data, as I have seen violin plots with thick lines.

**Comment by adkinsrs** [comment]
This was resolved in in a past gEAR commit
