### ISSUE TITLE
"gEAR" labels still on NeMO page

### ISSUE THREAD

**Issue by carlocolantuoni** [nemoarchive/analytics#124]
in the pull down menu, when mousing over the "upload gene expression data" - it says "add data to gEAR"

when mousing over the NeMO graphic to go back to the NeMO home page is says "gEAR Home"

every line in the current (newly changed) NeMO gene expression uploader has "upload to gEAR"

**Comment by jorvis** [comment]
I've addressed the ones I could find with this commit.  Not in production yet.

https://github.com/jorvis/gEAR/commit/8f1a40cdedceb975d9c0df9ac136bf7180bff7c1
