### ISSUE TITLE
multiple views of the same dataset in a single profile

### ISSUE THREAD

**Issue by carlocolantuoni** [nemoarchive/analytics#129]
i am sure this has been brought up before, but it would be very useful to have multiple views of a dataset in a single profile without having to upload an entirely new instance of the data set. the static tSNE is a version of this, but if we could create a way to make an entirely new customizable view(s) of the same data set it would enable a large number of powerful visualizations.

i realize this might entail significant re-working of how the profile pages are constructed, so this should be a discussion before software engineering.

**Comment by jorvis** [comment]
Yes, already recorded here:

https://github.com/jorvis/gEAR/issues/357
