### ISSUE TITLE
Create sample bigwig and bigbed files

### ISSUE THREAD

**Issue by RLC-DCPPC** [nemoarchive/analytics#14]
From NeMO-Analytics created by [RLC-DCPPC](https://github.com/RLC-DCPPC) : RLC-DCPPC/NeMO-Analytics#13  

create some sample bigwig and bigbed files from NeMO dato to test ingest in to EpiVIZ

zhang data?

**Comment by RLC-DCPPC** [comment]
- [ ] assign to apaala
- [ ] put InProgress in Sprint 2

**Comment by apaala** [comment]
The zeng bigwigs I had deposited in incoming have not been pushed to DMZ yet. The directory structure exists but there are no files:
/local/projects-t3/NEMO/dmz/brain/biccn/grant/zeng/zeng/transcriptome/scell/SMARTer/processed/bigwig/MOs/
Shaun said they would be pushed into dmz next time he performs a bundle.

RoadMap bigbeds:
/local/projects-t3/NEMO/incoming/brain/other/grant/epigenome_roadmap/epigenome_roadmap/chipseq/bulk/processed/align

Some test bigwigs I had initially generated for methylation data a long time ago:
http://data.nemoarchive.org/biccn/grant/cemba/ecker/methylation/scell/processed/align/4B/CEMBA171212_4B/bigwigs/

Some test bigwigs I had initially generated for atac-seq data a long time ago:
 http://data.nemoarchive.org/biccn/grant/cemba/ecker/chromatin/scell/processed/align/3C/CEMBA171207_3C/

**Comment by jkanche** [comment]
@apaala, Those two formats work on epiviz. Having some metadata/annotations on these files would be helpful.

**Comment by jkanche** [comment]
@casalex or @apaala , can you post the link to the processed chromHMM tracks here ?

**Comment by apaala** [comment]
@jkanche Im not sure what chromHMM data you are talking about. If it is the Roadmap data, then you should be able to access it here:
http://data.nemoarchive.org/other/grant/epigenome_roadmap/epigenome_roadmap/chipseq/bulk/processed/align/

**Comment by casalex** [comment]
@jkanche I thought the chromHMM tracks were already pulled for your epiviz demo? I have a few of the brain-specific 25-state imputed model on hand locally if you need more.

**Comment by jkanche** [comment]
@casalex, can you update the metadata file for the roadmap data ? 

The chromHMM tracks are not on nemo/epiviz, I downloaded a few locally the last time I showed them. I also tried to just query the files from roadmap's FTP server, but I think they have a limit on the number of requests you can make and so the requests get blocked. If you could drop these on nemo archive somewhere, that would be great. Thanks!

**Comment by casalex** [comment]
@jkanche What needs to be updated on the Roadmap side? IIRC I subset it to be only the ones you have a couple weeks ago. Where specifically would you like me to put the chromHMM?

**Comment by jkanche** [comment]
The metadata file available here (http://data.nemoarchive.org/other/grant/epigenome_roadmap/epigenome_roadmap/chipseq/bulk/processed/align/metadata.tsv.tar) has over 500 rows but the number of files in the roadmap set is close to a 100. If you can create another metadata for only the files available that would be good. 

anywhere on nemo, but may be aapaala or anup can help with the actual location ?

**Comment by casalex** [comment]
I believe the metadata issue was resolved here a couple weeks ago here, but I only tagged apaala: https://github.com/nemoarchive/analytics/issues/23#issuecomment-472528614

Let me know if that works.

**Comment by jkanche** [comment]
@apaala will this also get pushed to public next wednesday ?

**Comment by jkanche** [comment]
@Seth Can you let me know which roadmap & chromHMM tracks you would like to embed in gEAR ?

**Comment by seth-ament** [comment]
@jkanche please start with the samples from fetal brain. The file accessions from Alex's metadata file are as follows. These are ChIP-seq of fetal brain at 17.5 gestational weeks.
ENCFF265PQT
ENCFF826SJK
ENCFF487KNS
ENCFF757GHZ
ENCFF307KHT
ENCFF485CBV
ENCFF799AEV

**Comment by apaala** [comment]
@jkanche  @casalex http://data.nemoarchive.org/biccn/grant/zeng/zeng/transcriptome/scell/SMARTer/processed/bigwig/MOs/

I copied the new metadata.tsv and it can be found in http://data.nemoarchive.org/other/grant/epigenome_roadmap/epigenome_roadmap/chipseq/bulk/processed/align/

**Comment by jkanche** [comment]
@apaala any metadata available for the scell data ?

**Comment by apaala** [comment]
@jkanche I am not too familiar with the dataset apart from generating the bigwigs, I will ask around, or we can bring it up in standup see if anyone knows

**Comment by seth-ament** [comment]
Metadata from the BICCN studies is very limited right now. We are waiting for the BICCN coordinating center to send more detailed metadata. Please note that the single-cell data are not required for the current sprint to the BRAIN Initiative meeting.
