### ISSUE TITLE
Can a permalink for a profile point directly to the view of that profile rather than the homepage?

### ISSUE THREAD

**Issue by seth-ament** [nemoarchive/analytics#142]
I've heard from a number of people that it is a source of confusion that the permalinks we provide point to the gEAR/NeMO homepage, rather than a page that directly displays a view of the dataset. For instance, the following was a reviewer comment on our Huntington's disease single-nucleus RNA-seq manuscript:
"The link https://umgear.org/p?l=1d76bf3e takes me to an apparently general single-cell RNA-seq portal that contains several different data sets but nothing that appears connected to this work."
In fact, the URL correctly points to a page where the Huntington's disease profile I created is selected on the homepage. However, to an untrained user, it is not at all clear that one should type in a gene name to see all the datasets. Indeed, I am not at all surprised this reviewer was unable to figure that out.
Is there any way to have the URL directly load the multi-dataset view of this profile? E.g., by pre-selecting an example gene to display, then loading the view of that gene?

**Comment by jorvis** [comment]
Yes.  Example:

https://umgear.org/p?l=1d76bf3e&g=gad2

Notice I only added &g=gad2 to the URL.
