### ISSUE TITLE
Add links to Cell x Gene profiles

### ISSUE THREAD

**Issue by brianherb** [nemoarchive/analytics#152]
Add button to BICCN profiles on nemo analytics to link to Cell x Gene page of that same data. Ambrose Carr and the cell x gene team has curated a number of BICCN datasets for the cell x gene viewer. They created a url for each dataset (but not to a specific gene) that we can use to link to their pages. Ambrose also gave us permission to use the cell x gene logo. 

This button can be added to the drop down menu for a given dataset (prefered):
![image](https://user-images.githubusercontent.com/13540148/115874803-8b65c000-a412-11eb-8bc9-2bc68aa1dfd4.png)

and/or added to the background of the profile:
![image](https://user-images.githubusercontent.com/13540148/115874751-79841d00-a412-11eb-9e3e-c5087e3c78f6.png)

We can test this for one dataset - the 'Primary Motor Cortex from Mouse - 10X_cells_v2_AIBS' dataset in the 'BICCN Mini-Atlas (Transcript)' profile. 

Nemo Analytics ID for Primary Motor Cortex from Mouse - 10X_cells_v2_AIBS: 
8eb9cd46-a5c8-40e6-983b-8809eb1201cc

Cell x gene page:
https://cellxgene.cziscience.com/e/c88e2a9c-72b8-4a88-a2f6-e428eada0c86.cxg/

**Comment by brianherb** [comment]
Here is a lookup table for Nemo datasets that have a corresponding cell x gene page 

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:////Users/bherb/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

<link rel=themeData
href="file:////Users/bherb/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:////Users/bherb/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>




Nemo   Dataset | Cell   x gene page
-- | --
8eb9cd46-a5c8-40e6-983b-8809eb1201cc | https://cellxgene.cziscience.com/e/c88e2a9c-72b8-4a88-a2f6-e428eada0c86.cxg/
72b8e735-6ac2-4e0d-919a-c989994f8be1 | https://cellxgene.cziscience.com/e/5e765f97-1cf1-407e-a86c-e28701f4749d.cxg/
bf902ed4-b163-4495-85fa-eea46e4d5670 | https://cellxgene.cziscience.com/e/50d79de5-bd17-4d14-a295-199d71ff56be.cxg/
495d68ba-9c05-4f5a-8b39-fb62291ae205 | https://cellxgene.cziscience.com/e/a9affc92-a291-4eb9-996f-147392132323.cxg/
a430009a-6fbc-b343-6103-8955d8bc8dac | https://cellxgene.cziscience.com/e/ad5cd6ca-06c0-41cb-9b18-4638a05a0990.cxg/
a430009a-6fbc-b343-6103-8955d8bc8dac | https://cellxgene.cziscience.com/e/31dd355c-3140-4558-a648-7e1e5f00480b.cxg/




</body>

</html>

**Comment by brianherb** [comment]
Additional links:





<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:////Users/bherb/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel="File-List" href="file:////Users/bherb/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>


<meta charset="utf-8">




Description | Nemo Link | Nemo Dataset | Cell x gene page
-- | -- | -- | --
Mouse MOp Merfish | https://nemoanalytics.org/p?l=7e14ad94 | 88d1fa92-fa74-aea5-5540-004f87718650 | https://cellxgene.cziscience.com/e/257adc73-8152-414b-a2c7-73861b8e0c0a.cxg/
Human MOp Inhibitory | https://nemoanalytics.org/p?l=ac9863bf | fcd8186e-f26f-493e-acc2-19e49edae191 | https://cellxgene.cziscience.com/e/f7a068f1-0fdb-48e8-8029-db870ff11d9e.cxg/
Human MOp Excitatory | https://nemoanalytics.org/p?l=ac9863bf | dd7e9b4b-b127-4447-8d41-9fd16c954119 | https://cellxgene.cziscience.com/e/6acb6637-ac08-4a65-b2d1-581e51dc7ccf.cxg/
Human MOp Excitatory | https://nemoanalytics.org/p?l=ac9863bf | dd7e9b4b-b127-4447-8d41-9fd16c954119 | https://cellxgene.cziscience.com/e/b6203114-e133-458a-aed5-eed1028378b4.cxg/
Human MOp Non-Neuron | https://nemoanalytics.org/p?l=ac9863bf | 12545384-48b1-454b-a210-8781ca3e2230 | https://cellxgene.cziscience.com/e/9b686bb6-1427-4e13-b451-7ee961115cf9.cxg/

**Comment by brianherb** [comment]
favicon for cellxgene: 
https://cellxgene.cziscience.com/e/c88e2a9c-72b8-4a88-a2f6-e428eada0c86.cxg/static/assets/favicon-16x16.png 

or on grid at /local/projects-t3/idea/bherb/NeMO_work/cellxgene/favicon-16x16.png

**Comment by brianherb** [comment]
favicon for Single cell portal:
https://singlecell.broadinstitute.org/single_cell/assets/scp_favicon-1d789652ef8c200e339a406bdb39d8caee8e3659cebd427b52998f88c9bf9235.ico

or on grid at /local/projects-t3/idea/bherb/NeMO_work/SingelCellPortal/SCP_favicon.ico

**Comment by brianherb** [comment]
Don't worry about Single cell portal for now - datasets have not been uploaded to that site yet. However, cellxgene is ready to go.

**Comment by jorvis** [comment]
I have added support for this (not visible until the next release) but have added a screenshot below.  This add support for CellxGene, Single-cell portal, and a 'general' class of links.  This can be expanded more as needed.

![Screenshot from 2021-10-04 13-43-40](https://user-images.githubusercontent.com/330899/135906921-fda662ae-d561-41bb-96ea-c3203909c8ce.png)

Links currently come from the database_link table in MySQL but there isn't yet a GUI interface to manage these.  That will need to be added to the Dataset Explorer.
