### ISSUE TITLE
cant generate permalink for new profiles

### ISSUE THREAD

**Issue by carlocolantuoni** [nemoarchive/analytics#156]
hi guys,
when i hit the "share layout profile", it says "URL copied to clipboard", but when i paste all i get is:
https://nemoanalytics.org/p?l=undefined
am i doin something wrong?

**Comment by carlocolantuoni** [comment]
it now appears to be working, but i was having a lot of trouble creating a new profile - it seemed to add many datasets to the new profile automatically - or i couldnt tell why lots of profiles were listed when i looked only for datasets in the profile. not sure what was going on - i was very confused.

**Comment by jorvis** [comment]
Carlo - Let me know if you want to have a call and screenshare issues here this week.
