### ISSUE TITLE
Ingest Kriegstein 10X data

### ISSUE THREAD

**Issue by RLC-DCPPC** [nemoarchive/analytics#17]
From NeMO created by [seth-ament](https://github.com/seth-ament) : jorvis/NeMO#18

**Comment by RLC-DCPPC** [comment]
For pre-merge comment trail see original issue linked in description.

**Comment by jorvis** [comment]
Under which named profile for the front page should this dataset be loaded?

**Comment by jorvis** [comment]
@RLC-DCPPC is Brian H. not part of this Nemo Analytics project?  He created all the notes from the source of this ticket:

https://github.com/jorvis/NeMO/issues/18

But I had further questions and can't tag him here.

From that ticket I see a directory of 41 different files to load.  Which are part of this ticket?

/local/projects-t3/NEMO/incoming/brain/biccc/kriegstein500k/transcriptome/scell/processed/counts/for_gEAR

**Comment by apaala** [comment]
@jorvis, @RLC-DCPPC is going to reach out to Victor to add him to this repo

**Comment by jorvis** [comment]
Closing this as loading notes are also in issue #23 but with epigenetic data too
