### ISSUE TITLE
Ingest Kriegstein 6K Science Paper Singler Cell

### ISSUE THREAD

**Issue by RLC-DCPPC** [nemoarchive/analytics#20]
From NeMO created by [RLC-DCPPC](https://github.com/RLC-DCPPC) : jorvis/NeMO#3  

Subtask of (https://github.com/jorvis/NeMO/issues/1)

- [ ] Ingest Kriegstein 6K Science Paper Singler Cell

**Comment by RLC-DCPPC** [comment]
For pre-merge comment trail see original issue linked in description.

**Comment by carlocolantuoni** [comment]
@RLC-DCPPC @jorvis 
this is done and is at:
/local/encrypted/NEMO/incoming/brain/development/ARK/ARKctxDevo3Ksc

**Comment by jorvis** [comment]
Comment from Carlo in the older ticket (jorvis/NeMO#3)

"I cant see this data set (ARKctxDevo3Ksc) in gear-devel.nemoanalytics - or
the tSNE type scatter plot in the curator that we need for this data as
well as for the Kriegstein 10x data sets (4) and the scESCdifBifurcCelSeq2k"

**Comment by jorvis** [comment]
Stuck on this one.  The genes meta file has ensembl IDs, which is great, but the data matrix is indexed on gene symbol.  Normally I've just made the transformation, but here there are duplicate genes in the matrix index which map to different ensembl IDs, but it's not possible to tell which one correlates to which gene.  Example:

```
$ grep YWHAE ARKctxDevo3Ksc_DataMTX.tab | cut -f 1-3 
YWHAE	6.02794579450484	8.91980187594881
YWHAE	6.02794579450484	8.17274151692647

$ grep YWHAE ARKctxDevo3Ksc_ROWmeta.tab | cut -f 1-5
YWHAE	ENSG00000274474.3	ENSG00000274474	7531	YWHAE
YWHAE	ENSG00000108953.16	ENSG00000108953	7531	YWHAE
```

In later Ensembl releases they often renamed these with suffixes like -1 and -2, but I just checked these two accessions and they remain just like this.

**Comment by jorvis** [comment]
Update:  For this dataset @carlocolantuoni reports that the rows are in sync between the two files, so I can just use that.  (kudos to the linux paste command)

**Comment by jorvis** [comment]
Loading finished here.  I'll add an item in #32 for tSNE to be added.
[ARKctxDevo3Ksc.NOTES.txt](https://github.com/nemoarchive/analytics/files/3024046/ARKctxDevo3Ksc.NOTES.txt)

**Comment by carlocolantuoni** [comment]
@jorvis - i just updated the files for this kriegstein 3.4(6)k data - i corrected some oddities in the cell type classes by adding "majortype4" column to the column meta data - this is the one we should use to color the tSNE - can you bring the files into NeMO Analytics again? /local/encrypted/NEMO/incoming/brain/development/ARK/ARKctxDevo3Ksc/

**Comment by jorvis** [comment]
I have reprocessed this one and replaced it.
