### ISSUE TITLE
Load Cortecon dataset

### ISSUE THREAD

**Issue by jorvis** [nemoarchive/analytics#24]
Shifted from issue #23 , keeping notes here on loading The Cortecon dataset.  From Carlo:

/local/encrypted/NEMO/incoming/brain/development/NSCI/Cortecon/

**Comment by jorvis** [comment]
This dataset lacked Ensembl IDs so I'm doing a mapping based on gene symbols.  It has 44562 gene rows, but comparing these names with all Ensembl releases between 74 - 94 the best match is release 76, in which 23404 of the genes are accounted for.  That seems like a lot, but when I look at the gene symbol column in the source file 21672 of them have 'NA' as the gene symbol.  

@seth-ament - OK to load these and omit these unmappable genes?

**Comment by carlocolantuoni** [comment]
I think thats fine

**Comment by seth-ament** [comment]
Yes, please go ahead and upload with all the genes you've been able to map.


________________________________

**Comment by jorvis** [comment]
This one is loaded and placed into the Neocortical Development profile.

**Comment by seth-ament** [comment]
Hi Joshua,


Looks nice! And thanks for getting the quantitative x-axis working!


Who has permissions to set the default view for these datasets? I tried to set up the CORTECON dataset with violin plots as the default, but I can't figure out now to save my view.


Thanks!


Seth


________________________________

**Comment by jorvis** [comment]
The quantitative X-axis support shouldn't be ready yet unless Brian G. snuck it in without me noticing.

And the dataset owner has the rights to set the default views for them.  I just ran through and set default violin profiles on them all for now.  Do you want me to change the ownership to you instead?

**Comment by seth-ament** [comment]
Hi Joshua,


Could you make Brian H. the owner for the 10x datasets and me the owner for CORTECON?

Thanks!

Seth

________________________________

**Comment by jorvis** [comment]
Done.   There's a bit of a flow issue after you make the layout where you have to go back into it in order to choose a default layout.  Brian G will be fixing that.

**Comment by jorvis** [comment]
This has been loaded for a while, but closing and attaching notes file here.
[Cortecon.NOTES.txt](https://github.com/nemoarchive/analytics/files/3008896/Cortecon.NOTES.txt)

**Comment by seth-ament** [comment]
I have added a default view for this dataset. (violin plot with a quantitative x-axis)

**Comment by jorvis** [comment]
@carlocolantuoni Did you have tSNE data for this dataset? I only see the following columns in the COLmeta data file and no supplemental ones:

dataColNames    Day     Rep     color

**Comment by seth-ament** [comment]
no tSNE for this one. it is standard mRNA-seq, not sc.
