### ISSUE TITLE
Load scESCdifBifurcCelSeq2k dataset

### ISSUE THREAD

**Issue by jorvis** [nemoarchive/analytics#25]
Shifted from issue #23 , keeping notes for this dataset here.

**Comment by jorvis** [comment]
@carlocolantuoni I'm a little confused about this dataset - What do you imagine its primary display method to be?  The column metadata file has no grouping columns or any with continuous data for XY scatter.  I'm going to keep loading it in case tSNE will be the main display, but was just curious.

**Comment by seth-ament** [comment]
Hi Josh,

Yes, the primary display for this would probably be tSNE.

Carlo, is there a published clustering / tSNE view of the dataset to which you have access, or will be need to cluster it ourselves?

**Comment by carlocolantuoni** [comment]
There are tSNE1 and tSNE2 columns in the the COLmeta, but the PCA is
actually ideal for this dataset which is in the COLmeta_DIMRED_PCA which is
a file not currently brought into gEAR. If its a pain to bring that in we
can use tSNE.

**Comment by jorvis** [comment]
Initial load of this dataset is complete (owned by Seth), and I've added it to the Neocortical Development profile.  I'll continue working on the tSNE (and possibly PCA) bits.

**Comment by jorvis** [comment]
Adding notes and closing, since the tSNE support is being tracked in task #32

**Comment by jorvis** [comment]
[scESCdifBifurcCelSeq2k.NOTES.txt](https://github.com/nemoarchive/analytics/files/3022927/scESCdifBifurcCelSeq2k.NOTES.txt)

**Comment by carlocolantuoni** [comment]
@jorvis - i just updated the files for this scESCdifBifurcCelSeq2k data - the PC1 and PC2 are now also in the standard Column meta data so we will be able to use them in creating the scatter view. can you bring the files into NeMO Analytics again? /local/encrypted/NEMO/incoming/brain/development/Broad/scESCdifBifurcCelSeq2k/

**Comment by carlocolantuoni** [comment]
@jorvis @seth-ament 
hey seth , once joshua gets the updated version in, can u as the owner make a new view scattering by PC1 and PC2 - i think that will best for coloring by day and when we want to color by expression - it shows precursors and neurons separated on PC1 and time on PC2.

**Comment by jorvis** [comment]
I have replaced this with the new version.
