### ISSUE TITLE
gear-devel.nemoarchive.org site flagged as not secure

### ISSUE THREAD

**Issue by seth-ament** [nemoarchive/analytics#26]

**Comment by seth-ament** [comment]
When loading the page one gets a warning from Chrome, since the certificate is from umgear.org.

**Comment by jorvis** [comment]
Victor - we actually want to move this VM to gear-devel.nemoanalytics.org.  Can you get on the VM (GCP) and make the necessary SSL changes there if the cert already exists?

**Comment by victor73** [comment]
@jorvis I'm not seeing any VM instances. Which GCP project are these VMs in?

**Comment by jorvis** [comment]
It's in the nemo analytics one.  I can add you, but which email address do you prefer?

**Comment by victor73** [comment]
Let's do the work email/account if possible.

**Comment by jorvis** [comment]
I've added you as project editor.

**Comment by victor73** [comment]
Should be good now.
