### ISSUE TITLE
cosmetic changes to nemo analytics front page

### ISSUE THREAD

**Issue by seth-ament** [nemoarchive/analytics#27]
- [x] Create a NeMO Analytics logo (presumably closely related to the NeMO Archive logo) --> task for Lance?
- [x] Switch "home" button logo in upper-left corner from gEAR to NeMO Analytics logo
- [x] List NeMO funding sources at the bottom of the home page: 1R24MH114815-01A1, 1R24MH114788-01
- [x] "Highlighted dataset" on front page is a cochlea dataset from gEAR...
- [x] The "About" paragraph at the top of the front page needs to be updated to describe NeMO Analytics
- [x] Add a "powered by gEAR" link somewhere on the page with a link to umgear.org

**Comment by RLC-DCPPC** [comment]
might look like this example: https://gcid.umgear.org

**Comment by RLC-DCPPC** [comment]
Link to NeMO data portal

**Comment by seth-ament** [comment]
NIMH logo (for funding): https://commons.wikimedia.org/wiki/File:US-NIH-NIMH-Logo.svg

**Comment by seth-ament** [comment]
As the highlighted dataset, let's use "Single-cell mRNA sequencing (scRNA-seq - 10X) in Prefrontal Cortex of individual at gestational week 19".

**Comment by seth-ament** [comment]
"About" paragraph:
https://docs.google.com/document/d/10S4oHun0QpGOUe5iad2zrJnTz425VMWu4FwJBqN8_D0/edit?usp=sharing

**Comment by seth-ament** [comment]
About (updated 4/1 4pm)

The Neuroscience Multi-Omic (NeMO) Analytics portal enables web-based visualization and analysis of multi-omic data describing cell types in the developing and adult brain, powered by gEAR (umgear.org) and Epiviz (https://epiviz.github.io/). Release 1 (April 2019) includes single-cell and bulk tissue RNA-seq, ATAC-seq, and ChIP-seq from the fetal human prefrontal cortex, as well as from stem cell models of neural induction. The portal will expand to include multiple regions of the developing and adult brain and additional analytical tools. For more information, please see the <<User Manual>> and <<Tutorials>>.

**Comment by jorvis** [comment]
@seth-ament - Do you have an image you want me to use for the highlighted dataset?

**Comment by seth-ament** [comment]
Let's use a screenshot of the tSNE colored by cell type, once we get that updated tomorrow morning.

**Comment by jorvis** [comment]
This was completed some time ago.
