### ISSUE TITLE
Can't save displays in Dataset Curator

### ISSUE THREAD

**Issue by seth-ament** [nemoarchive/analytics#28]
I am trying to use the Curate tool to create a display for the CORTECON dataset (H9 ESC neural differentiation RNA-seq). It allows me to select violin plot, choose a gene (EOMES), and the grouping variable (day). However, the dialog box to name the display and save it does not appear.

I checked and these features seem to be working fine at umgear.org, so it may be an issue specific to nemoanalytics.org.

Working in Chrome on a Mac.

**Comment by carlocolantuoni** [comment]
I have the same problem as well

**Comment by seth-ament** [comment]
This appears to be resolved as of this morning.
