### ISSUE TITLE
add external resource links

### ISSUE THREAD

**Issue by seth-ament** [nemoarchive/analytics#30]

**Comment by seth-ament** [comment]
1) Remove link to SHIELD
2) Change ENSEMBL link so that it links to the human (rather than mouse) gene
3) Change UniProt link so that it links to the human rather than mouse gene
4) Add link to CORTECON: http://cortecon.neuralsci.org
5) Add link to UCSC Cell Browser: https://cells.ucsc.edu/?ds=cortex-dev
6) Add link to BrainSpan: http://www.brainspan.org/rnaseq/search/index.html

**Comment by jorvis** [comment]
UCSC example URL with gene: https://cells.ucsc.edu/?ds=cortex-dev&gene=GFAP

**Comment by jorvis** [comment]
These links are all added and can be seen on the devel site.  The Ensembl and UniProt links actually have human paths already, but the issue here is that the organism 'mouse' is chosen by default on the page.  Looking into a clean way to make this select human first instead, then will close this.

**Comment by seth-ament** [comment]
The new links  look terrific! Thanks, Joshua!
