### ISSUE TITLE
Add support for pre-computed tSNE

### ISSUE THREAD

**Issue by jorvis** [nemoarchive/analytics#32]
When this is done, we also need to load into the following datasets:

- [x] #25 scESCdifBifurcCelSeq2k
- [x] #20 ARKctxDevo3Ksc

**Comment by carlocolantuoni** [comment]
I think cortecon is in already, that the in vitro bulk neural
differentiation

**Comment by jorvis** [comment]
First tested (in Jupyter) version of a script to add this support is here:

https://github.com/jorvis/gEAR/commit/53c8a7175ae64230fcc59cf3afac9ff0fbb258f6

**Comment by jorvis** [comment]
Changing assignment to Brian for Curator support.

**Comment by carlocolantuoni** [comment]
brian G has set this up nicely - the discrete individual coloring option (rather than purple shaded scale) when working to color by cell class/category is one of the last things we need for the demo

**Comment by carlocolantuoni** [comment]
sorry - didnt tag any one:
@jorvis @briangottfried 
brian G has set this up nicely - the discrete individual coloring option (rather than purple shaded scale) when working to color by cell class/category is one of the last things we need for the demo

**Comment by briangottfried** [comment]
@carlocolantuoni Fixed. Using a 20 categorical color scale. If there are more than 20 levels it cycles back to the first color.

**Comment by carlocolantuoni** [comment]
Great thnx

**Comment by carlocolantuoni** [comment]
hey all - for each of the single cell data sets it is very hard to see anything in the plots when we have 8 panels open. as we discussed yesterday, making the points smaller will help, but we might want to think of how to make all these data sets easily viewable when there is so much on the screen at once. might not be pressing if we can make individual screen shots work for the demo.

**Comment by jorvis** [comment]
I agree, there's a fundamental conflict in trying to display data this dense but in a compact form alongside other datasets.  Remember that you can also use the context menu in the upper right of any dataset and select the 'View' option to get a view of that dataset which fills all the panels.

**Comment by carlocolantuoni** [comment]
Ya, we should use that for a lot of he screen shots I think

**Comment by jorvis** [comment]
Closing as completed, but tSNE support has been added and these datasets have been loaded.
