### ISSUE TITLE
comparison tool not working

### ISSUE THREAD

**Issue by seth-ament** [nemoarchive/analytics#36]
I tried using the comparison tool to visualize samples from the POU3F2oe and H9 ESC differentiation datasets, but I get the error shown on the attached screenshot.
[nemo_analytics_comparison_tool_error.pdf](https://github.com/nemoarchive/analytics/files/3031032/nemo_analytics_comparison_tool_error.pdf)

**Comment by briangottfried** [comment]
![image](https://user-images.githubusercontent.com/10342878/55514056-22e1f580-5635-11e9-8e18-385cdb460158.png)
Should this [commit](https://github.com/jorvis/gEAR/commit/33f8a06d80be43c927d32888645ee93667a4b540) should fix this.
