### ISSUE TITLE
single-cell workbench not working

### ISSUE THREAD

**Issue by seth-ament** [nemoarchive/analytics#38]
Currently the single-cell workbench is not working, at least for the couple datasets I've tried. It is getting stuck on the first cell filtering step. For the GW19 10X dataset I get "Error: Internal server error". For the ARK3.4k dataset it's been spinning for several minutes and doesn't give any result.
[scworkbench-error.pdf](https://github.com/nemoarchive/analytics/files/3040917/scworkbench-error.pdf)

**Comment by jorvis** [comment]
Can you verify that this is still an issue for you?  I see Victor was doing some things with the server to enable SSL which might be completed now.  It worked when I tried it (attached)
![Screenshot from 2019-04-03 17-18-15](https://user-images.githubusercontent.com/330899/55516972-8cadcf80-5634-11e9-8ce5-3f1de23b11e6.png)

**Comment by seth-ament** [comment]
ok, yeah, it's working again now. thanks!
