### ISSUE TITLE
set default displays for 10X datasets

### ISSUE THREAD

**Issue by seth-ament** [nemoarchive/analytics#39]
@brianherb You are the owner of the 10X datasets in NeMO Analytics. The curator for the 10X datasets is now (mostly) working. Could you please create displays for each datasets? We discussed two displays for each: 
1) tSNE colored by Cell Annotation
2) tSNE colored by expression

In addition, I think it would be great to create a 3rd display showing a violin plot grouped by Cell Annotation.

Could you please set up those displays by tomorrow and set them as default?

**Comment by brianherb** [comment]
Gene expression for Pou3f2?

**Comment by seth-ament** [comment]
I set the ones I "own" so that the display gene is EOMES, but any neurodevelopment gene is fine.

**Comment by brianherb** [comment]
Displays are created - but I'm now confused by the site - can I only access non-default plots via the curator? Does an option exist to just view all plots created for a given sample? 

To match with other plots, I'll just make the tSNE expression the default for now.

**Comment by seth-ament** [comment]
Thanks, Brian! There's a bug that's preventing a popup from appearing to toggle between displays (just added a new ticket for this). In the meantime, a few minor tweaks:

1) could you edit the tSNE displays so that the tick mark labels are not displayed, for consistency with the other tSNEs?
2) I still don't see default displays for the following datasets: "Single-cell mRNA sequencing (scRNA-seq - 10X) in Prefrontal Cortex of individual at Carnegie Stage 22" and "scRNAseq of human prefrontal cortex at GW18". Could you add displays for those ones, as well?

**Comment by brianherb** [comment]
1. tick marks are gone now

2. I'll run the cell scoring and tSNE for CS22 and GW18 this morning -

**Comment by brianherb** [comment]
@jorvis - Hi Josh, I've created new h5ad files for GW18 (scRNAseq of human prefrontal cortex at GW18) and CS22 (Single-cell mRNA sequencing (scRNA-seq - 10X) in Prefrontal Cortex of individual at Carnegie Stage 22)  - these now include tSNE coordinates and cell type assignments like the other Kriegstein datasets. 

Files:

## CS22:
/local/projects-t3/NEMO/incoming/brain/biccc/kriegstein500k/transcriptome/scell/processed/counts/for_gEAR/CS22_PFC_tsne.h5ad

/local/projects-t3/NEMO/incoming/brain/biccc/kriegstein500k/transcriptome/scell/processed/counts/for_gEAR/CS22_PFC_meta.json


## GW18:
/local/projects-t3/NEMO/incoming/brain/biccc/kriegstein500k/transcriptome/scell/processed/counts/for_gEAR/GW18_PFC_tsne.h5ad

/local/projects-t3/NEMO/incoming/brain/biccc/kriegstein500k/transcriptome/scell/processed/counts/for_gEAR/GW18_PFC_meta.json

**Comment by jorvis** [comment]
I have replaced both CS22 and GW18.

**Comment by brianherb** [comment]
Thank you @jorvis! @seth-ament  - All Kriegstein 10X datasets have displays
