### ISSUE TITLE
"reorder display" not working in the curator

### ISSUE THREAD

**Issue by seth-ament** [nemoarchive/analytics#40]
@briangottfried I am trying to create a violin plot for one of the 10X datasets, grouped by Cell Annotation. I would like the groups to be displayed in the order:
RG, tRG, vRG, oRG, IPC, nEN, EN, MGE, nIN, IN, OPC, Astrocyte, Microglia, nan
I can drag the group labels around, but when I press "Reorder Display" it just resets to the default order. Can you help?

**Comment by briangottfried** [comment]
Should be fixed now with this [commit](https://github.com/jorvis/gEAR/commit/f856f5a35a80a3fae69d58f877e128df6663ae6d).

**Comment by seth-ament** [comment]
Yes -- working well now. Thank you!
