### ISSUE TITLE
premalink not working 

### ISSUE THREAD

**Issue by hertzron** [nemoarchive/analytics#45]
https://gear-devel.nemoanalytics.org/p?s=c4b59c43-1946-4fc4-aa4e-0e5c0b099898

**Comment by jorvis** [comment]
Working notes .... I see in the apache error logs that it's a config issue:

AH00670: Options FollowSymLinks and SymLin
ksIfOwnerMatch are both off, so the RewriteRule directive is also forbidden due to its similar ability to circumvent directory rest
rictions : /var/www/p

**Comment by hertzron** [comment]
what does this mean?

**Comment by jorvis** [comment]
It's notes for myself as I go.

**Comment by jorvis** [comment]
This is an issue on both normal gear and nemo versions

**Comment by jorvis** [comment]
Fix on both gear-devel and production gear.

**Comment by hertzron** [comment]
thanks!
