### ISSUE TITLE
change owner just for screen shots

### ISSUE THREAD

**Issue by hertzron** [nemoarchive/analytics#46]
Joshua - can yo uplease change me to be owner of Dorsolateral Prefrontal Cortex Development RNA-seq (Jaffe et al. 2018 Nat Neurosci) so that I can share it etc for screen shots? you can then switch back to Seth or can discuss having 'Analytics Curator' like we did for gEAR - where a select group of people can access the portal as 'curators' this way don't have to keep switching ownership if collaborating on data handling

**Comment by jorvis** [comment]
Done.  Dataset ID is 61ea9b06-3d44-4878-a5cb-6f51a36c77b2
