### ISSUE TITLE
Standardize metadata

### ISSUE THREAD

**Issue by RLC-DCPPC** [nemoarchive/analytics#5]
From NeMO-Analytics created by [RLC-DCPPC](https://github.com/RLC-DCPPC) : RLC-DCPPC/NeMO-Analytics#3  

- [ ] Need a better description and an estimate (0,1/2,1,2,3,5,8,13,20,40,100).

- [x] Assign to carlo and joshua

we need (Kriegstien and Brainspan) - need vector based tSNE (JO

**Comment by RLC-DCPPC** [comment]
- [ ] assign to carlo
- [ ] add to ToDo in Sprint 2

**Comment by jorvis** [comment]
@carlocolantuoni or Seth (Why can't I tag seth, I don't see his user name?)  Can we elaborate on what this ticket is for?  We seem to have achieved standardization of both what's in each dataset and the metadata file.  What's missing?

**Comment by RLC-DCPPC** [comment]
@jorvis : Seth has an outstanding invitation, but I just added him as a collaborator so he should have a fresh one (added Ronna as well; Brian Herb is already a collaborator).

**Comment by carlocolantuoni** [comment]
Donr kno
I think we are ok here
