### ISSUE TITLE
Perform Mapping of genes to Ensembl IDs at IGS instead of Google Server

### ISSUE THREAD

**Issue by apaala** [nemoarchive/analytics#53]
In order to generate tabix files for expression datasets, we need to map the geneIDs to Ensembl IDs. For this we need to be able to access the database generated by @jorvis that is currently hosted on google, and perform the mapping to the correct Ensembl release.

**Comment by jorvis** [comment]
We have created a clone of the database which houses the annotation information at IGS and I have given Apaala the credentials.  She has used this to test run getting the best matching ensembl release, so it appears to be working.  I'll leave this to close when it is incorporated completely at the cron.

**Comment by jkanche** [comment]
is this using the script from here ? 

https://github.com/nemoarchive/analytics/issues/15#issuecomment-495041032

**Comment by jorvis** [comment]
Your is to add coordinates for tabix, right?  This is an upstream processing step on the initial data to simply add ensembl IDs to a file which doesn't have them.  I know yours can use ensembl IDs or gene symbols, but our software stack requires the files to be indexed on Ensembl ID (gene symbols are there too).

[Script used](https://github.com/jorvis/gEAR/blob/master/bin/add_ensembl_ids_to_tab_file.py)
