### ISSUE TITLE
directory missing: /local/encrypted/NEMO/incoming/brain/development/

### ISSUE THREAD

**Issue by carlocolantuoni** [nemoarchive/analytics#55]
the directory:
/local/encrypted/NEMO/incoming/brain/development/
no longer exists.
whats going on here?

**Comment by apaala** [comment]
I wasn't able to find the "development" folder in the "other" folder. Here is where I looked:
/local/projects-t3/NEMO/incoming/brain/other
/local/encrypted/NEMO/incoming/brain/other

**Comment by apaala** [comment]
The folder has been moved to /local/projects-t3/NEMO/incoming/brain/other/grant/development/
