### ISSUE TITLE
Ingest MOpR sncell transcriptome data from Macosko lab

### ISSUE THREAD

**Issue by brianherb** [nemoarchive/analytics#58]
32 mex files with file names pBICCNsMMrMOpR*.mex.tar.gz can be ingested into NeMO analytics. Path on grid: 

/local/projects-t3/NEMO/dmz/brain/biccn/lab/macosko/transcriptome/sncell/processed/counts 

Don't know much about the samples, but Evan noted that these are from the primary motor cortex, and the letter in the file name after MOpR is either "A", "M", or "P", corresponding to the subregion Anterior, Medial, or Posterior. Oddly, I don't think Seth is part of this hub, but you can email him for further info on the samples.

**Comment by seth-ament** [comment]
I watch all the activity on the NeMO Analytics (and gEAR) GitHub repos and comment frequently, but for some reason it doesn't see me as a member of the team...

Does it make any sense to merge the data into three samples ("A", "M", and "P") prior to uploading?

**Comment by jorvis** [comment]
I'll leave that up to you two - Uploading 3 would definitely be preferred to 32 separate datasets.

**Comment by brianherb** [comment]
What I can do is merge cells within each region and create 5had files that we can then upload to nemo analytics.

**Comment by brianherb** [comment]
I created h5ad files by merging and downsampling samples from each region down to 10K cells. Files are here: 

*Anterior:*
local/projects-t3/idea/bherb/NeMO_work/Macosko/h5ad/MOpR_Anterior_10X_SN_Macosko_meta.json

local/projects-t3/idea/bherb/NeMO_work/Macosko/h5ad/Atot_count_norm_10000cells.h5ad 


*Medial:*
local/projects-t3/idea/bherb/NeMO_work/Macosko/h5ad/MOpR_Medial_10X_SN_Macosko_meta.json

local/projects-t3/idea/bherb/NeMO_work/Macosko/h5ad/Mtot_count_norm_10000cells.h5ad


*Posterior:*
local/projects-t3/idea/bherb/NeMO_work/Macosko/h5ad/MOpR_Posterior_10X_SN_Macosko_meta.json

local/projects-t3/idea/bherb/NeMO_work/Macosko/h5ad/Ptot_count_norm_10000cells.h5ad

**Comment by brianherb** [comment]
@jorvis  - This might have fallen through the cracks since I closed the ticket - were these datasets added to nemo analytics?

**Comment by jorvis** [comment]
These have been put on both nemo-devel and production, currently marked as private and owned by the NeMO Curator user.  If they should be made public and part of any profiles, let me know.
