### ISSUE TITLE
PCA projectR: write a script to precompute PCA on datasets during upload 

### ISSUE THREAD

**Issue by RLC-DCPPC** [nemoarchive/analytics#59]
PCA projectR: write a script to precompute PCA on datasets during upload and store the results in the h5ad object. Note: Until this is implemented, any front-end task would be blocked. (Brian)
***** this would be very easy to implement - we just need to decide if we also want to do some very basic quality filtering of the cells at the same time - for example kicking out cells that have less than X number of reads...etc. 

Once this is in place:
A]  a "dimension reduction" pull down menu for all data sets to view existing and generate more dimension reduction analyses.
B]  a "projection" pull down enabled for each data set for which dimension reduction exists where user can select what dimensions to project into other selected data sets in Analytics.

**Comment by brianherb** [comment]
Wrote a CGI script that heavily borrows from existing CGI scripts written for single cell workbench - the script calculates PCA for dataset and saves results under 'uns' slot.  

[https://github.com/nemoarchive/analytics/blob/master/projectR/Calc_Dim_Reduction.cgi](url)
