### ISSUE TITLE
uploading additional datasets into gEAR

### ISSUE THREAD

**Issue by RLC-DCPPC** [nemoarchive/analytics#61]
--cortical neurogenesis datasets (Carlo)

--primary motor cortex datasets (Brian)

******* one hangup with the miniatlas data - In the dropbox folder, the tsne.df.csv (tsne coordinates) file for single-cell SMART-seq (Allen) is empty - can we request that the Allen re-upload this file?

**Comment by brianherb** [comment]
Are there datasets not mentioned in tickets #56 and #58 that still require processing?

**Comment by brianherb** [comment]
I believe all datasets have been uploaded
