### ISSUE TITLE
curator not loading available views?

### ISSUE THREAD

**Issue by seth-ament** [nemoarchive/analytics#63]
I am logged in as nemo curator and am trying to curate the dataset "Primary Motor Cortex from Mouse - Single Cell SMARTer RNAseq". It is stuck on "loading available displays" for several minutes and has not provided the dropdown.

**Comment by briangottfried** [comment]
https://gear-devel.nemoanalytics.org/dataset_curator.html#/dataset/e7eff83d-1274-4780-b5ea-263f1c22ae54/displays/new Should be working now.

**Comment by seth-ament** [comment]
thanks -- yes, it's working now.
