### ISSUE TITLE
MOPs datasets do not show up as available for analysis with the scWorkbench

### ISSUE THREAD

**Issue by seth-ament** [nemoarchive/analytics#65]
None of the private single-cell datasets from the primary motor cortex show up in the scWorkbench.... e.g., Macosko Lab Primary Motor Cortex (Posterior) from Mouse Single Nuclei 10X RNAseq, Primary Motor Cortex from Mouse - Single Cell SMARTer RNAseq. Primary Motor Cortex from Human - Single nuclei 10X RNAseq, etc.

**Comment by jorvis** [comment]
That's because they're not marked as public and you don't own them.  Should they be public?

**Comment by jorvis** [comment]
Right now they're owned by the NeMO Curator account.

**Comment by seth-ament** [comment]
I was logged in as the NeMO Curator when I had this issue. Can you see if you can replicate the issue?

**Comment by jorvis** [comment]
Could you try again now?  It looks like the datatypes may have been wrong.  I don't believe I have the login information for that service account unless someone wants to mail it to me (don't put it here please.)

**Comment by seth-ament** [comment]
I can now see the primary motor cortex datasets in the scWorkbench dropdown, but I get an error when I try to load them. I get the same error for all these datasets:

Action log
Failed ID was: 22cec0a6-bc8c-4743-a38c-9fb18374133c because msg: Internal Server Error
Failed to access dataset

**Comment by jorvis** [comment]
I updated all the code on devel and then tested - there were a few issues, but many of these larger datasets will not currently load on production due to memory limitations.  The devel server though can currently handle them.  After my updates, the first three I tried loaded:

https://gear-devel.nemoanalytics.org/analyze_dataset.html
