### ISSUE TITLE
Control color of plots in side-by-side plots

### ISSUE THREAD

**Issue by brianherb** [nemoarchive/analytics#78]
It would be nice to add the ability to both adjust the range of colors on the gene expression plot and allow the user to use their own colors for the cluster plot. Right now, the blue-white-red range for gene expression causes middle-expressed genes to be washed out(displaying as white). Also, since we are hosting miniatlas data - it would be good to use the colors they use in their publications.

**Comment by seth-ament** [comment]
Agreed. The default color scheme here should be a single-gradient (e.g., white-->red) not a double-gradient (e.g., blue-->white-->red).
