### ISSUE TITLE
Correction to a dataset in the HRP profile

### ISSUE THREAD

**Issue by hertzron** [nemoarchive/analytics#84]
Joshua/Yang - please see note from Jenny Stone:

Hey Ronna,

Please relabel this dataset as Adult USC (utricular extrastriolar SC) versus NUSC (striolar SC and HC)

(I.e. NOT "rest of utricle”)

Jenny

![image](https://user-images.githubusercontent.com/17456863/71218066-2afac780-228e-11ea-943a-e682cae6482a.png)

**Comment by jorvis** [comment]
I have done this. (and I assume you meant for this to be within gEAR rather than NeMO Analytics.
