### ISSUE TITLE
Find moved files - cron uploader

### ISSUE THREAD

**Issue by apaala** [nemoarchive/analytics#85]
If a file has been moved from the path that is indicated in the log file, we need to use the diff file to find the new path. They will have the tag "CHANGED_DIR" in the diff file.

**Comment by apaala** [comment]
@jorvis This is the issue I was referring to in #90

**Comment by apaala** [comment]
@adkinsrs This ticket is referencing the issue where if a moved file is encountered the uploader fails. The uploader needs to be updated to find the changed path from your diff files.

**Comment by adkinsrs** [comment]
My solution for this is based on using NeMO identifiers as input to upload data.  I plan on having a cronjob run where if any file in DMZ is moved the "file_url" field (referencing http://data.nemoarchive.org) in the NeMO identifiers database will be adjusted.  In the upload script this file_url is converted back to the filepath.

**Comment by adkinsrs** [comment]
Several different methods can be used to upload files, but we are currently only focused on GEO submissions for now.  Closing and will reopen if this is still an issue.
