### ISSUE TITLE
JSON metadata flexibility- metadatavalidator.py/cron uploader

### ISSUE THREAD

**Issue by apaala** [nemoarchive/analytics#87]
The metadata validator rejects files that don't allow a very specific format. That might be hard to get everyone to do. Jayaram mentions Json Schema, which can help with that issue. (example of a scenario is when a field is given "" value.)

**Comment by jkanche** [comment]
a library to validate json schemas - https://json-schema.org/

They have implementations for different languages

**Comment by apaala** [comment]
@adkinsrs The metadata validator part of the process is highly specific and easily fails if the format is not exactly right. Since that will be hard to implement we want to make it more flexible. This script is part of the gear git.

**Comment by adkinsrs** [comment]
I am going to close for now.  Given my experiences for loosening up restrictions for submissions on the NeMO Archive side and how that made more work for the analysts and myself, I would rather err on the side of keep validation script as it ensures the underlying code receives nothing out-of-the-ordinary.

If this is still an issue that should be addressed please either reopen the ticket or just create a new one.
