### ISSUE TITLE
Spiny gear DB -cron uploader

### ISSUE THREAD

**Issue by apaala** [nemoarchive/analytics#88]
Check to see if the DB is running otherwise we do the analysis and create files but the script fails.

**Comment by RLC-DCPPC** [comment]
@adkinsrs, @apalla :  Just noticed this was reopened awhile ago. Anything to do here?

**Comment by apaala** [comment]
I think @adkinsrs fixed this... It is a ticket to ensure that the database which is used to determine en release is running.
