### ISSUE TITLE
Single-dataset 'View' is not working

### ISSUE THREAD

**Issue by seth-ament** [nemoarchive/analytics#94]
Thumbnails load extremely fast, but when I click View for a dataset it fails to display. Tested dataset is 'Primary Motor Cortex from Mouse - 10X_cells_v3_AIBS'.

**Comment by jorvis** [comment]
Can you give a bit more information here?  What page were you on when you
saw these thumbnails?  View button on which page?

**Comment by seth-ament** [comment]
This seems to be an issue for all the datasets on the BICCN Integrated and BICCN Molecular profiles. The older Cortical Development profile continues to work fine. The View button I'm referring to is the one on the dropdown in the upper-right hand corner of the thumbnail. When I click the button, I see the banner for the dataset, but it never loads the tSNE image.

**Comment by seth-ament** [comment]
@jorvis this is still an issue. Any progress on diagnosing the problem? I would like to get it fixed this week, since the paper describing these datasets is going to be posted on bioRxiv with a link to NeMO Analytics.

**Comment by jorvis** [comment]
No, I haven't looked at it.  Thanks for letting me know it's on a priority list though.

**Comment by seth-ament** [comment]
Appreciate the help. Thanks!

**Comment by adkinsrs** [comment]
Believe this is a memory error via generating the zoomed plot.   This also occurs in the gEAR portal as well for tSNE plots.

`[Wed Feb 26 18:11:41.278289 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549] [2020-02-26 18:11:41,249] ERROR in app: Exception on /plot/c4f16a12-9e98-47be-4335-b8321282919e/tsne [GET]
[Wed Feb 26 18:11:41.281671 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549] Traceback (most recent call last):
[Wed Feb 26 18:11:41.281682 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]   File "/home/jorvis/git/gEAR/www/api/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
[Wed Feb 26 18:11:41.281685 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]     rv = self.dispatch_request()
[Wed Feb 26 18:11:41.281688 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]   File "/home/jorvis/git/gEAR/www/api/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
[Wed Feb 26 18:11:41.281692 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Feb 26 18:11:41.281694 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]   File "/home/jorvis/git/gEAR/www/api/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
[Wed Feb 26 18:11:41.281697 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]     resp = resource(*args, **kwargs)
[Wed Feb 26 18:11:41.281700 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]   File "/home/jorvis/git/gEAR/www/api/env/lib/python3.7/site-packages/flask/views.py", line 88, in view
[Wed Feb 26 18:11:41.281703 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]     return self.dispatch_request(*args, **kwargs)
[Wed Feb 26 18:11:41.281712 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]   File "/home/jorvis/git/gEAR/www/api/env/lib/python3.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
[Wed Feb 26 18:11:41.281715 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]     resp = meth(*args, **kwargs)
[Wed Feb 26 18:11:41.281717 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]   File "/home/jorvis/git/gEAR/www/api/resources/tsne_data.py", line 70, in get
[Wed Feb 26 18:11:41.281720 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]     adata = sc.read_h5ad(ana.dataset_path())
[Wed Feb 26 18:11:41.281722 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]   File "/home/jorvis/git/gEAR/www/api/env/lib/python3.7/site-packages/anndata/readwrite/read.py", line 452, in read_h5ad
[Wed Feb 26 18:11:41.281725 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]     return AnnData(*_read_args_from_h5ad(filename=filename, chunk_size=chunk_size), dtype=dtype)
[Wed Feb 26 18:11:41.281728 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]   File "/home/jorvis/git/gEAR/www/api/env/lib/python3.7/site-packages/anndata/readwrite/read.py", line 486, in _read_args_from_h5ad
[Wed Feb 26 18:11:41.281731 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]     _read_key_value_from_h5(f, d, key, chunk_size=chunk_size)
[Wed Feb 26 18:11:41.281734 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]   File "/home/jorvis/git/gEAR/www/api/env/lib/python3.7/site-packages/anndata/readwrite/read.py", line 518, in _read_key_value_from_h5
[Wed Feb 26 18:11:41.281736 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549]     value = np.empty(ds.shape, ds.dtype)
[Wed Feb 26 18:11:41.281738 2020] [wsgi:error] [pid 24960] [remote 134.192.135.254:61549] MemoryError`

**Comment by adkinsrs** [comment]
Opening branch "tSNE_zoom" to implement this request.  In a nutshell, what I found was the js/classes/display.js code block for drawing the zoomed tSNE image was creating the HTML template portion for the page, but was not creating the tSNE image.

**Comment by adkinsrs** [comment]
Pull Request issued in gEAR... Issue 646
